package com.kunfei.bookshelf.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kunfei.bookshelf.bean.BookSourceBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_SOURCE_BEAN".
*/
public class BookSourceBeanDao extends AbstractDao<BookSourceBean, String> {

    public static final String TABLENAME = "BOOK_SOURCE_BEAN";

    /**
     * Properties of entity BookSourceBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property BookSourceUrl = new Property(0, String.class, "bookSourceUrl", true, "BOOK_SOURCE_URL");
        public final static Property BookSourceName = new Property(1, String.class, "bookSourceName", false, "BOOK_SOURCE_NAME");
        public final static Property BookSourceGroup = new Property(2, String.class, "bookSourceGroup", false, "BOOK_SOURCE_GROUP");
        public final static Property BookSourceType = new Property(3, String.class, "bookSourceType", false, "BOOK_SOURCE_TYPE");
        public final static Property LoginUrl = new Property(4, String.class, "loginUrl", false, "LOGIN_URL");
        public final static Property LastUpdateTime = new Property(5, Long.class, "lastUpdateTime", false, "LAST_UPDATE_TIME");
        public final static Property SerialNumber = new Property(6, int.class, "serialNumber", false, "SERIAL_NUMBER");
        public final static Property Weight = new Property(7, int.class, "weight", false, "WEIGHT");
        public final static Property Enable = new Property(8, boolean.class, "enable", false, "ENABLE");
        public final static Property RuleFindUrl = new Property(9, String.class, "ruleFindUrl", false, "RULE_FIND_URL");
        public final static Property RuleFindList = new Property(10, String.class, "ruleFindList", false, "RULE_FIND_LIST");
        public final static Property RuleFindName = new Property(11, String.class, "ruleFindName", false, "RULE_FIND_NAME");
        public final static Property RuleFindAuthor = new Property(12, String.class, "ruleFindAuthor", false, "RULE_FIND_AUTHOR");
        public final static Property RuleFindKind = new Property(13, String.class, "ruleFindKind", false, "RULE_FIND_KIND");
        public final static Property RuleFindIntroduce = new Property(14, String.class, "ruleFindIntroduce", false, "RULE_FIND_INTRODUCE");
        public final static Property RuleFindLastChapter = new Property(15, String.class, "ruleFindLastChapter", false, "RULE_FIND_LAST_CHAPTER");
        public final static Property RuleFindCoverUrl = new Property(16, String.class, "ruleFindCoverUrl", false, "RULE_FIND_COVER_URL");
        public final static Property RuleFindNoteUrl = new Property(17, String.class, "ruleFindNoteUrl", false, "RULE_FIND_NOTE_URL");
        public final static Property RuleSearchUrl = new Property(18, String.class, "ruleSearchUrl", false, "RULE_SEARCH_URL");
        public final static Property RuleSearchList = new Property(19, String.class, "ruleSearchList", false, "RULE_SEARCH_LIST");
        public final static Property RuleSearchName = new Property(20, String.class, "ruleSearchName", false, "RULE_SEARCH_NAME");
        public final static Property RuleSearchAuthor = new Property(21, String.class, "ruleSearchAuthor", false, "RULE_SEARCH_AUTHOR");
        public final static Property RuleSearchKind = new Property(22, String.class, "ruleSearchKind", false, "RULE_SEARCH_KIND");
        public final static Property RuleSearchIntroduce = new Property(23, String.class, "ruleSearchIntroduce", false, "RULE_SEARCH_INTRODUCE");
        public final static Property RuleSearchLastChapter = new Property(24, String.class, "ruleSearchLastChapter", false, "RULE_SEARCH_LAST_CHAPTER");
        public final static Property RuleSearchCoverUrl = new Property(25, String.class, "ruleSearchCoverUrl", false, "RULE_SEARCH_COVER_URL");
        public final static Property RuleSearchNoteUrl = new Property(26, String.class, "ruleSearchNoteUrl", false, "RULE_SEARCH_NOTE_URL");
        public final static Property RuleBookUrlPattern = new Property(27, String.class, "ruleBookUrlPattern", false, "RULE_BOOK_URL_PATTERN");
        public final static Property RuleBookInfoInit = new Property(28, String.class, "ruleBookInfoInit", false, "RULE_BOOK_INFO_INIT");
        public final static Property RuleBookName = new Property(29, String.class, "ruleBookName", false, "RULE_BOOK_NAME");
        public final static Property RuleBookAuthor = new Property(30, String.class, "ruleBookAuthor", false, "RULE_BOOK_AUTHOR");
        public final static Property RuleCoverUrl = new Property(31, String.class, "ruleCoverUrl", false, "RULE_COVER_URL");
        public final static Property RuleIntroduce = new Property(32, String.class, "ruleIntroduce", false, "RULE_INTRODUCE");
        public final static Property RuleBookKind = new Property(33, String.class, "ruleBookKind", false, "RULE_BOOK_KIND");
        public final static Property RuleBookLastChapter = new Property(34, String.class, "ruleBookLastChapter", false, "RULE_BOOK_LAST_CHAPTER");
        public final static Property RuleChapterUrl = new Property(35, String.class, "ruleChapterUrl", false, "RULE_CHAPTER_URL");
        public final static Property RuleChapterUrlNext = new Property(36, String.class, "ruleChapterUrlNext", false, "RULE_CHAPTER_URL_NEXT");
        public final static Property RuleChapterList = new Property(37, String.class, "ruleChapterList", false, "RULE_CHAPTER_LIST");
        public final static Property RuleChapterName = new Property(38, String.class, "ruleChapterName", false, "RULE_CHAPTER_NAME");
        public final static Property RuleContentUrl = new Property(39, String.class, "ruleContentUrl", false, "RULE_CONTENT_URL");
        public final static Property RuleContentUrlNext = new Property(40, String.class, "ruleContentUrlNext", false, "RULE_CONTENT_URL_NEXT");
        public final static Property RuleBookContent = new Property(41, String.class, "ruleBookContent", false, "RULE_BOOK_CONTENT");
        public final static Property HttpUserAgent = new Property(42, String.class, "httpUserAgent", false, "HTTP_USER_AGENT");
    }


    public BookSourceBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookSourceBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_SOURCE_BEAN\" (" + //
                "\"BOOK_SOURCE_URL\" TEXT PRIMARY KEY NOT NULL ," + // 0: bookSourceUrl
                "\"BOOK_SOURCE_NAME\" TEXT," + // 1: bookSourceName
                "\"BOOK_SOURCE_GROUP\" TEXT," + // 2: bookSourceGroup
                "\"BOOK_SOURCE_TYPE\" TEXT," + // 3: bookSourceType
                "\"LOGIN_URL\" TEXT," + // 4: loginUrl
                "\"LAST_UPDATE_TIME\" INTEGER," + // 5: lastUpdateTime
                "\"SERIAL_NUMBER\" INTEGER NOT NULL ," + // 6: serialNumber
                "\"WEIGHT\" INTEGER NOT NULL ," + // 7: weight
                "\"ENABLE\" INTEGER NOT NULL ," + // 8: enable
                "\"RULE_FIND_URL\" TEXT," + // 9: ruleFindUrl
                "\"RULE_FIND_LIST\" TEXT," + // 10: ruleFindList
                "\"RULE_FIND_NAME\" TEXT," + // 11: ruleFindName
                "\"RULE_FIND_AUTHOR\" TEXT," + // 12: ruleFindAuthor
                "\"RULE_FIND_KIND\" TEXT," + // 13: ruleFindKind
                "\"RULE_FIND_INTRODUCE\" TEXT," + // 14: ruleFindIntroduce
                "\"RULE_FIND_LAST_CHAPTER\" TEXT," + // 15: ruleFindLastChapter
                "\"RULE_FIND_COVER_URL\" TEXT," + // 16: ruleFindCoverUrl
                "\"RULE_FIND_NOTE_URL\" TEXT," + // 17: ruleFindNoteUrl
                "\"RULE_SEARCH_URL\" TEXT," + // 18: ruleSearchUrl
                "\"RULE_SEARCH_LIST\" TEXT," + // 19: ruleSearchList
                "\"RULE_SEARCH_NAME\" TEXT," + // 20: ruleSearchName
                "\"RULE_SEARCH_AUTHOR\" TEXT," + // 21: ruleSearchAuthor
                "\"RULE_SEARCH_KIND\" TEXT," + // 22: ruleSearchKind
                "\"RULE_SEARCH_INTRODUCE\" TEXT," + // 23: ruleSearchIntroduce
                "\"RULE_SEARCH_LAST_CHAPTER\" TEXT," + // 24: ruleSearchLastChapter
                "\"RULE_SEARCH_COVER_URL\" TEXT," + // 25: ruleSearchCoverUrl
                "\"RULE_SEARCH_NOTE_URL\" TEXT," + // 26: ruleSearchNoteUrl
                "\"RULE_BOOK_URL_PATTERN\" TEXT," + // 27: ruleBookUrlPattern
                "\"RULE_BOOK_INFO_INIT\" TEXT," + // 28: ruleBookInfoInit
                "\"RULE_BOOK_NAME\" TEXT," + // 29: ruleBookName
                "\"RULE_BOOK_AUTHOR\" TEXT," + // 30: ruleBookAuthor
                "\"RULE_COVER_URL\" TEXT," + // 31: ruleCoverUrl
                "\"RULE_INTRODUCE\" TEXT," + // 32: ruleIntroduce
                "\"RULE_BOOK_KIND\" TEXT," + // 33: ruleBookKind
                "\"RULE_BOOK_LAST_CHAPTER\" TEXT," + // 34: ruleBookLastChapter
                "\"RULE_CHAPTER_URL\" TEXT," + // 35: ruleChapterUrl
                "\"RULE_CHAPTER_URL_NEXT\" TEXT," + // 36: ruleChapterUrlNext
                "\"RULE_CHAPTER_LIST\" TEXT," + // 37: ruleChapterList
                "\"RULE_CHAPTER_NAME\" TEXT," + // 38: ruleChapterName
                "\"RULE_CONTENT_URL\" TEXT," + // 39: ruleContentUrl
                "\"RULE_CONTENT_URL_NEXT\" TEXT," + // 40: ruleContentUrlNext
                "\"RULE_BOOK_CONTENT\" TEXT," + // 41: ruleBookContent
                "\"HTTP_USER_AGENT\" TEXT);"); // 42: httpUserAgent
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_SOURCE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookSourceBean entity) {
        stmt.clearBindings();
 
        String bookSourceUrl = entity.getBookSourceUrl();
        if (bookSourceUrl != null) {
            stmt.bindString(1, bookSourceUrl);
        }
 
        String bookSourceName = entity.getBookSourceName();
        if (bookSourceName != null) {
            stmt.bindString(2, bookSourceName);
        }
 
        String bookSourceGroup = entity.getBookSourceGroup();
        if (bookSourceGroup != null) {
            stmt.bindString(3, bookSourceGroup);
        }
 
        String bookSourceType = entity.getBookSourceType();
        if (bookSourceType != null) {
            stmt.bindString(4, bookSourceType);
        }
 
        String loginUrl = entity.getLoginUrl();
        if (loginUrl != null) {
            stmt.bindString(5, loginUrl);
        }
 
        Long lastUpdateTime = entity.getLastUpdateTime();
        if (lastUpdateTime != null) {
            stmt.bindLong(6, lastUpdateTime);
        }
        stmt.bindLong(7, entity.getSerialNumber());
        stmt.bindLong(8, entity.getWeight());
        stmt.bindLong(9, entity.getEnable() ? 1L: 0L);
 
        String ruleFindUrl = entity.getRuleFindUrl();
        if (ruleFindUrl != null) {
            stmt.bindString(10, ruleFindUrl);
        }
 
        String ruleFindList = entity.getRuleFindList();
        if (ruleFindList != null) {
            stmt.bindString(11, ruleFindList);
        }
 
        String ruleFindName = entity.getRuleFindName();
        if (ruleFindName != null) {
            stmt.bindString(12, ruleFindName);
        }
 
        String ruleFindAuthor = entity.getRuleFindAuthor();
        if (ruleFindAuthor != null) {
            stmt.bindString(13, ruleFindAuthor);
        }
 
        String ruleFindKind = entity.getRuleFindKind();
        if (ruleFindKind != null) {
            stmt.bindString(14, ruleFindKind);
        }
 
        String ruleFindIntroduce = entity.getRuleFindIntroduce();
        if (ruleFindIntroduce != null) {
            stmt.bindString(15, ruleFindIntroduce);
        }
 
        String ruleFindLastChapter = entity.getRuleFindLastChapter();
        if (ruleFindLastChapter != null) {
            stmt.bindString(16, ruleFindLastChapter);
        }
 
        String ruleFindCoverUrl = entity.getRuleFindCoverUrl();
        if (ruleFindCoverUrl != null) {
            stmt.bindString(17, ruleFindCoverUrl);
        }
 
        String ruleFindNoteUrl = entity.getRuleFindNoteUrl();
        if (ruleFindNoteUrl != null) {
            stmt.bindString(18, ruleFindNoteUrl);
        }
 
        String ruleSearchUrl = entity.getRuleSearchUrl();
        if (ruleSearchUrl != null) {
            stmt.bindString(19, ruleSearchUrl);
        }
 
        String ruleSearchList = entity.getRuleSearchList();
        if (ruleSearchList != null) {
            stmt.bindString(20, ruleSearchList);
        }
 
        String ruleSearchName = entity.getRuleSearchName();
        if (ruleSearchName != null) {
            stmt.bindString(21, ruleSearchName);
        }
 
        String ruleSearchAuthor = entity.getRuleSearchAuthor();
        if (ruleSearchAuthor != null) {
            stmt.bindString(22, ruleSearchAuthor);
        }
 
        String ruleSearchKind = entity.getRuleSearchKind();
        if (ruleSearchKind != null) {
            stmt.bindString(23, ruleSearchKind);
        }
 
        String ruleSearchIntroduce = entity.getRuleSearchIntroduce();
        if (ruleSearchIntroduce != null) {
            stmt.bindString(24, ruleSearchIntroduce);
        }
 
        String ruleSearchLastChapter = entity.getRuleSearchLastChapter();
        if (ruleSearchLastChapter != null) {
            stmt.bindString(25, ruleSearchLastChapter);
        }
 
        String ruleSearchCoverUrl = entity.getRuleSearchCoverUrl();
        if (ruleSearchCoverUrl != null) {
            stmt.bindString(26, ruleSearchCoverUrl);
        }
 
        String ruleSearchNoteUrl = entity.getRuleSearchNoteUrl();
        if (ruleSearchNoteUrl != null) {
            stmt.bindString(27, ruleSearchNoteUrl);
        }
 
        String ruleBookUrlPattern = entity.getRuleBookUrlPattern();
        if (ruleBookUrlPattern != null) {
            stmt.bindString(28, ruleBookUrlPattern);
        }
 
        String ruleBookInfoInit = entity.getRuleBookInfoInit();
        if (ruleBookInfoInit != null) {
            stmt.bindString(29, ruleBookInfoInit);
        }
 
        String ruleBookName = entity.getRuleBookName();
        if (ruleBookName != null) {
            stmt.bindString(30, ruleBookName);
        }
 
        String ruleBookAuthor = entity.getRuleBookAuthor();
        if (ruleBookAuthor != null) {
            stmt.bindString(31, ruleBookAuthor);
        }
 
        String ruleCoverUrl = entity.getRuleCoverUrl();
        if (ruleCoverUrl != null) {
            stmt.bindString(32, ruleCoverUrl);
        }
 
        String ruleIntroduce = entity.getRuleIntroduce();
        if (ruleIntroduce != null) {
            stmt.bindString(33, ruleIntroduce);
        }
 
        String ruleBookKind = entity.getRuleBookKind();
        if (ruleBookKind != null) {
            stmt.bindString(34, ruleBookKind);
        }
 
        String ruleBookLastChapter = entity.getRuleBookLastChapter();
        if (ruleBookLastChapter != null) {
            stmt.bindString(35, ruleBookLastChapter);
        }
 
        String ruleChapterUrl = entity.getRuleChapterUrl();
        if (ruleChapterUrl != null) {
            stmt.bindString(36, ruleChapterUrl);
        }
 
        String ruleChapterUrlNext = entity.getRuleChapterUrlNext();
        if (ruleChapterUrlNext != null) {
            stmt.bindString(37, ruleChapterUrlNext);
        }
 
        String ruleChapterList = entity.getRuleChapterList();
        if (ruleChapterList != null) {
            stmt.bindString(38, ruleChapterList);
        }
 
        String ruleChapterName = entity.getRuleChapterName();
        if (ruleChapterName != null) {
            stmt.bindString(39, ruleChapterName);
        }
 
        String ruleContentUrl = entity.getRuleContentUrl();
        if (ruleContentUrl != null) {
            stmt.bindString(40, ruleContentUrl);
        }
 
        String ruleContentUrlNext = entity.getRuleContentUrlNext();
        if (ruleContentUrlNext != null) {
            stmt.bindString(41, ruleContentUrlNext);
        }
 
        String ruleBookContent = entity.getRuleBookContent();
        if (ruleBookContent != null) {
            stmt.bindString(42, ruleBookContent);
        }
 
        String httpUserAgent = entity.getHttpUserAgent();
        if (httpUserAgent != null) {
            stmt.bindString(43, httpUserAgent);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookSourceBean entity) {
        stmt.clearBindings();
 
        String bookSourceUrl = entity.getBookSourceUrl();
        if (bookSourceUrl != null) {
            stmt.bindString(1, bookSourceUrl);
        }
 
        String bookSourceName = entity.getBookSourceName();
        if (bookSourceName != null) {
            stmt.bindString(2, bookSourceName);
        }
 
        String bookSourceGroup = entity.getBookSourceGroup();
        if (bookSourceGroup != null) {
            stmt.bindString(3, bookSourceGroup);
        }
 
        String bookSourceType = entity.getBookSourceType();
        if (bookSourceType != null) {
            stmt.bindString(4, bookSourceType);
        }
 
        String loginUrl = entity.getLoginUrl();
        if (loginUrl != null) {
            stmt.bindString(5, loginUrl);
        }
 
        Long lastUpdateTime = entity.getLastUpdateTime();
        if (lastUpdateTime != null) {
            stmt.bindLong(6, lastUpdateTime);
        }
        stmt.bindLong(7, entity.getSerialNumber());
        stmt.bindLong(8, entity.getWeight());
        stmt.bindLong(9, entity.getEnable() ? 1L: 0L);
 
        String ruleFindUrl = entity.getRuleFindUrl();
        if (ruleFindUrl != null) {
            stmt.bindString(10, ruleFindUrl);
        }
 
        String ruleFindList = entity.getRuleFindList();
        if (ruleFindList != null) {
            stmt.bindString(11, ruleFindList);
        }
 
        String ruleFindName = entity.getRuleFindName();
        if (ruleFindName != null) {
            stmt.bindString(12, ruleFindName);
        }
 
        String ruleFindAuthor = entity.getRuleFindAuthor();
        if (ruleFindAuthor != null) {
            stmt.bindString(13, ruleFindAuthor);
        }
 
        String ruleFindKind = entity.getRuleFindKind();
        if (ruleFindKind != null) {
            stmt.bindString(14, ruleFindKind);
        }
 
        String ruleFindIntroduce = entity.getRuleFindIntroduce();
        if (ruleFindIntroduce != null) {
            stmt.bindString(15, ruleFindIntroduce);
        }
 
        String ruleFindLastChapter = entity.getRuleFindLastChapter();
        if (ruleFindLastChapter != null) {
            stmt.bindString(16, ruleFindLastChapter);
        }
 
        String ruleFindCoverUrl = entity.getRuleFindCoverUrl();
        if (ruleFindCoverUrl != null) {
            stmt.bindString(17, ruleFindCoverUrl);
        }
 
        String ruleFindNoteUrl = entity.getRuleFindNoteUrl();
        if (ruleFindNoteUrl != null) {
            stmt.bindString(18, ruleFindNoteUrl);
        }
 
        String ruleSearchUrl = entity.getRuleSearchUrl();
        if (ruleSearchUrl != null) {
            stmt.bindString(19, ruleSearchUrl);
        }
 
        String ruleSearchList = entity.getRuleSearchList();
        if (ruleSearchList != null) {
            stmt.bindString(20, ruleSearchList);
        }
 
        String ruleSearchName = entity.getRuleSearchName();
        if (ruleSearchName != null) {
            stmt.bindString(21, ruleSearchName);
        }
 
        String ruleSearchAuthor = entity.getRuleSearchAuthor();
        if (ruleSearchAuthor != null) {
            stmt.bindString(22, ruleSearchAuthor);
        }
 
        String ruleSearchKind = entity.getRuleSearchKind();
        if (ruleSearchKind != null) {
            stmt.bindString(23, ruleSearchKind);
        }
 
        String ruleSearchIntroduce = entity.getRuleSearchIntroduce();
        if (ruleSearchIntroduce != null) {
            stmt.bindString(24, ruleSearchIntroduce);
        }
 
        String ruleSearchLastChapter = entity.getRuleSearchLastChapter();
        if (ruleSearchLastChapter != null) {
            stmt.bindString(25, ruleSearchLastChapter);
        }
 
        String ruleSearchCoverUrl = entity.getRuleSearchCoverUrl();
        if (ruleSearchCoverUrl != null) {
            stmt.bindString(26, ruleSearchCoverUrl);
        }
 
        String ruleSearchNoteUrl = entity.getRuleSearchNoteUrl();
        if (ruleSearchNoteUrl != null) {
            stmt.bindString(27, ruleSearchNoteUrl);
        }
 
        String ruleBookUrlPattern = entity.getRuleBookUrlPattern();
        if (ruleBookUrlPattern != null) {
            stmt.bindString(28, ruleBookUrlPattern);
        }
 
        String ruleBookInfoInit = entity.getRuleBookInfoInit();
        if (ruleBookInfoInit != null) {
            stmt.bindString(29, ruleBookInfoInit);
        }
 
        String ruleBookName = entity.getRuleBookName();
        if (ruleBookName != null) {
            stmt.bindString(30, ruleBookName);
        }
 
        String ruleBookAuthor = entity.getRuleBookAuthor();
        if (ruleBookAuthor != null) {
            stmt.bindString(31, ruleBookAuthor);
        }
 
        String ruleCoverUrl = entity.getRuleCoverUrl();
        if (ruleCoverUrl != null) {
            stmt.bindString(32, ruleCoverUrl);
        }
 
        String ruleIntroduce = entity.getRuleIntroduce();
        if (ruleIntroduce != null) {
            stmt.bindString(33, ruleIntroduce);
        }
 
        String ruleBookKind = entity.getRuleBookKind();
        if (ruleBookKind != null) {
            stmt.bindString(34, ruleBookKind);
        }
 
        String ruleBookLastChapter = entity.getRuleBookLastChapter();
        if (ruleBookLastChapter != null) {
            stmt.bindString(35, ruleBookLastChapter);
        }
 
        String ruleChapterUrl = entity.getRuleChapterUrl();
        if (ruleChapterUrl != null) {
            stmt.bindString(36, ruleChapterUrl);
        }
 
        String ruleChapterUrlNext = entity.getRuleChapterUrlNext();
        if (ruleChapterUrlNext != null) {
            stmt.bindString(37, ruleChapterUrlNext);
        }
 
        String ruleChapterList = entity.getRuleChapterList();
        if (ruleChapterList != null) {
            stmt.bindString(38, ruleChapterList);
        }
 
        String ruleChapterName = entity.getRuleChapterName();
        if (ruleChapterName != null) {
            stmt.bindString(39, ruleChapterName);
        }
 
        String ruleContentUrl = entity.getRuleContentUrl();
        if (ruleContentUrl != null) {
            stmt.bindString(40, ruleContentUrl);
        }
 
        String ruleContentUrlNext = entity.getRuleContentUrlNext();
        if (ruleContentUrlNext != null) {
            stmt.bindString(41, ruleContentUrlNext);
        }
 
        String ruleBookContent = entity.getRuleBookContent();
        if (ruleBookContent != null) {
            stmt.bindString(42, ruleBookContent);
        }
 
        String httpUserAgent = entity.getHttpUserAgent();
        if (httpUserAgent != null) {
            stmt.bindString(43, httpUserAgent);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BookSourceBean readEntity(Cursor cursor, int offset) {
        BookSourceBean entity = new BookSourceBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // bookSourceUrl
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bookSourceName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bookSourceGroup
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // bookSourceType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // loginUrl
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // lastUpdateTime
            cursor.getInt(offset + 6), // serialNumber
            cursor.getInt(offset + 7), // weight
            cursor.getShort(offset + 8) != 0, // enable
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // ruleFindUrl
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ruleFindList
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // ruleFindName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // ruleFindAuthor
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // ruleFindKind
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // ruleFindIntroduce
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // ruleFindLastChapter
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // ruleFindCoverUrl
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // ruleFindNoteUrl
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // ruleSearchUrl
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // ruleSearchList
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // ruleSearchName
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // ruleSearchAuthor
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // ruleSearchKind
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // ruleSearchIntroduce
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // ruleSearchLastChapter
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // ruleSearchCoverUrl
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // ruleSearchNoteUrl
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // ruleBookUrlPattern
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // ruleBookInfoInit
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // ruleBookName
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // ruleBookAuthor
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // ruleCoverUrl
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // ruleIntroduce
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // ruleBookKind
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // ruleBookLastChapter
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // ruleChapterUrl
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // ruleChapterUrlNext
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // ruleChapterList
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // ruleChapterName
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // ruleContentUrl
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // ruleContentUrlNext
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // ruleBookContent
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42) // httpUserAgent
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookSourceBean entity, int offset) {
        entity.setBookSourceUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBookSourceName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBookSourceGroup(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBookSourceType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLoginUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLastUpdateTime(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setSerialNumber(cursor.getInt(offset + 6));
        entity.setWeight(cursor.getInt(offset + 7));
        entity.setEnable(cursor.getShort(offset + 8) != 0);
        entity.setRuleFindUrl(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRuleFindList(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setRuleFindName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setRuleFindAuthor(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRuleFindKind(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setRuleFindIntroduce(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setRuleFindLastChapter(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setRuleFindCoverUrl(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setRuleFindNoteUrl(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setRuleSearchUrl(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setRuleSearchList(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setRuleSearchName(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setRuleSearchAuthor(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setRuleSearchKind(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setRuleSearchIntroduce(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setRuleSearchLastChapter(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setRuleSearchCoverUrl(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setRuleSearchNoteUrl(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setRuleBookUrlPattern(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setRuleBookInfoInit(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setRuleBookName(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setRuleBookAuthor(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setRuleCoverUrl(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setRuleIntroduce(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setRuleBookKind(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setRuleBookLastChapter(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setRuleChapterUrl(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setRuleChapterUrlNext(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setRuleChapterList(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setRuleChapterName(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setRuleContentUrl(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setRuleContentUrlNext(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setRuleBookContent(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setHttpUserAgent(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BookSourceBean entity, long rowId) {
        return entity.getBookSourceUrl();
    }
    
    @Override
    public String getKey(BookSourceBean entity) {
        if(entity != null) {
            return entity.getBookSourceUrl();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookSourceBean entity) {
        return entity.getBookSourceUrl() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
